### ISSUE TITLE
Simultaneous_Equations_Calculator/30_day_of_java

### ISSUE THREAD

**Issue by CLOUDyy003** [jitacm/-30DaysDevChallenge-#100]
# **Discription.**

The SimultaneousEquationsSolver program in Java is designed to solve a system of two linear equations with two variables using Cramer's rule. Linear equations are mathematical expressions that represent relationships between variables with constant coefficients. Solving these equations simultaneously means finding values for the variables that satisfy both equations at the same time.

# **The program performs the following steps:**

- **Introduction and User Prompt**: It introduces the user to the program and prompts them to enter the coefficients of the two linear equations.

- **Input Validation**: It ensures that the user inputs valid numerical values for the coefficients.

- **Solving the Equations**: It uses Cramer's rule to solve the system of equations. If a unique solution exists, the program calculates and displays the values of the variables (x) and (y). If no unique solution exists (i.e., if the determinant of the coefficient matrix is zero), the program informs the user.

- **Output**: It displays the solution in a user-friendly format.

**Comment by rohansnishad** [comment]
go ahead !
