### ISSUE TITLE
Alarm_Schedule_Manager/30_day_of_java

### ISSUE THREAD

**Issue by CLOUDyy003** [jitacm/-30DaysDevChallenge-#119]
**Description**
The Alarm Schedule Manager is a Java-based program designed to help you manage and schedule multiple tasks along with their respective alarm times. By integrating with the system clock, this program allows you to set alarms that trigger at specific times, providing an audible alert to remind you of important tasks.

**Comment by animex007** [comment]
go Ahead!

**Comment by CLOUDyy003** [comment]
Done, review it
