### ISSUE TITLE
 Object Tracking Project- 30 day to python

### ISSUE THREAD

**Issue by animex007** [jitacm/-30DaysDevChallenge-#12]
## Description
I am interested in developing an object-tracking project. The project will involve implementing various object-tracking methods and creating a comprehensive guide for users to understand and apply these techniques. The scope will include single object tracking (SOT) and multiple object tracking (MOT) methods, with example code and detailed documentation.

### Objectives
1. Implement Object Tracking Methods:

- Single Object Tracking (SOT)
        - Template Matching
        - Mean-Shift and CAMShift
        - Correlation Filters (e.g., MOSSE, KCF, CSRT)
- Multiple Object Tracking (MOT)
       - Kalman Filters
        - SORT (Simple Online and Realtime Tracking)
        - Deep SORT

**Comment by jitacm** [comment]
go ahead !
