### ISSUE TITLE
Tic-Tac-Toe Game / 30 days of Java

### ISSUE THREAD

**Issue by Shlokwankhade** [jitacm/-30DaysDevChallenge-#122]
# Tic-Tac-Toe Game

This is a simple command-line implementation of the classic Tic-Tac-Toe game in Java. The game allows two players to take turns marking spaces on a 3x3 board until one player wins by getting three marks in a row, column, or diagonal, or the board is full with no winner (resulting in a draw).

## Features

- **Interactive Gameplay:** Players take turns entering their moves via console input.
- **Winning Condition Detection:** The game checks after each move if a player has won by getting three marks in a row, column, or diagonal.
- **Input Validation:** Ensures that player moves are within valid board coordinates and on an empty space.
- **Clear Console Output:** Displays the current state of the board after each move, providing a clear view of the game progression.

**Comment by rohansnishad** [comment]
Tic-Tac-Toe Game Project is alrady created under JAVA
