### ISSUE TITLE
Tic-Tac-Toe Game/ 30_Days_of_Java

### ISSUE THREAD

**Issue by Mr-PratikTikhe** [jitacm/-30DaysDevChallenge-#139]
**Add GUI to Tic-Tac-Toe Game**

The Tic-Tac-Toe game currently runs in a console-based environment. This issue proposes adding a graphical user interface (GUI) using Java Swing to enhance user interaction and overall experience.

![unnamed](https://github.com/user-attachments/assets/d70df387-daef-4bcb-b166-cf7d7e993676)

**Comment by jitacm** [comment]
Go Ahead!
