### ISSUE TITLE
30-days of javascript/ To- Do-LIst 

### ISSUE THREAD

**Issue by animex007** [jitacm/-30DaysDevChallenge-#14]
# Create a To-Do List App in JavaScript 

## Summary:
I would like to propose the development of a new to-do list application. This app will help users manage their tasks efficiently with features such as task creation, editing, deletion, and prioritization.

## Features:

- Task Creation: Users can add new tasks with a title, description, and due date.
- Task Editing: Users can edit existing tasks.
- Task Deletion: Users can delete tasks they no longer need.
- Task Prioritization: Users can mark tasks with different priority levels (e.g., low, medium, high).

**Comment by jitacm** [comment]
Go ahead !
