### ISSUE TITLE
Snake_Game/30_Days_Of_Java

### ISSUE THREAD

**Issue by AnshNikhare** [jitacm/-30DaysDevChallenge-#142]
Issues in the Source Code:
Pop-Up Game-Over Message: The game-over message wasn't displayed correctly when the game ended.
Food Placement: Food could be placed on the snake's body, leading to unintended behavior.
Input Handling: The game did not correctly register and respond to user inputs.
Immediate Game Start: The game started immediately when the code was run, lacking user control.

**Changes in the Final Version:**
Game Over Pop-Up: Fixed the issue so the game over message now displays correctly.
Food Placement: Ensured food does not appear on the snake’s body.
Input Handling: Resolved the issue with input handling so user controls are now responsive.
Start and Difficulty Options: Added a start button and difficulty selection to control when the game begins and adjust difficulty settings.

![Screenshot 2024-07-20 224844](https://github.com/user-attachments/assets/224638e9-2bcd-4559-b150-644ca38a6c55)

**Comment by jitacm** [comment]
Go Ahead !
