### ISSUE TITLE
Simultaneous_Equation_Solver/30_Days_Of_Java

### ISSUE THREAD

**Issue by AnshNikhare** [jitacm/-30DaysDevChallenge-#152]
**Adding a Graphical User Interface (GUI) to the Simultaneous Equation Solver**
Currently, our equation solver operates in a console-based environment, which limits user interaction and experience. To enhance usability and make the tool more engaging, I propose adding a graphical user interface (GUI) using Java. This will provide a more intuitive and visually appealing way for users to interact with the equation solver, significantly improving the overall experience.

The attached image provides a preview of the proposed GUI design, showing how the interface will look after the code modification.

![image](https://github.com/user-attachments/assets/4d4730a6-b1d8-42ab-9241-e9f3dbb428ad)

**Comment by jitacm** [comment]
### Go Ahead !
## Note to Update the Readme.md , whenever necessary !
