### ISSUE TITLE
Password Strength Meter/30_Days_of_JavaScript

### ISSUE THREAD

**Issue by Bharat00007** [jitacm/-30DaysDevChallenge-#168]
**Password Strength Indicator**

I have created a small project called password strength indicator using HTML, CSS & JavaScript . A password strength checker has been added to provide users with real-time feedback on the security of their passwords. The checker categorizes passwords into "Weak", "Average" and "Strong" based on criteria like character variety and length. Additionally, it includes a toggle feature for password visibility.

![image_2024-07-26_222819809](https://github.com/user-attachments/assets/8cf1f775-ea2b-4f19-b530-e92f866991bd)

**Comment by Walayhs** [comment]
Go Ahead!
