### ISSUE TITLE
30_Day_of_Python/ Weather_App

### ISSUE THREAD

**Issue by animex007** [jitacm/-30DaysDevChallenge-#17]
# Create a Weather App

### **Description**:
I would like to create a Weather App using Python. This application will fetch and display weather information for a given city using the OpenWeatherMap API. The goal is to build a simple command-line interface that allows users to enter a city name and get current weather details such as temperature, pressure, humidity, and weather description.

## Features
- Prompt the user to enter a city name
- Fetch weather data from the OpenWeatherMap API
- Display the following information:
  - Temperature
  - Pressure
  - Humidity
  - Weather description
- Handle errors gracefully (e.g., city not found)

**Comment by jitacm** [comment]
sure , Go ahead !
