### ISSUE TITLE
Alarm Schedule Manager / 30_Days_Of_Java

### ISSUE THREAD

**Issue by AnshNikhare** [jitacm/-30DaysDevChallenge-#178]
# Issues in the source code:

- **File Not Found Error:** The program encountered a '_`FileNotFoundException`_' when trying to play the alarm sound. This was because the code did not specify the absolute path for the alarm.wav file.

- **Unsupported Audio File Format:** The code experienced an '_`UnsupportedAudioFileException`_' due to an incorrect or unsupported format of the alarm.wav file.

- **Unclosed Scanner:** The Scanner object used for user input was not closed, potentially leading to resource leaks.

- **Lack of GUI:** The original code lacked a graphical user interface (GUI), making it less user-friendly and harder to interact with for scheduling and managing alarm tasks.

**Comment by CLOUDyy003** [comment]
Go Ahead
