### ISSUE TITLE
Implement OTP Generator for 30 Days of Java Project / 30_Days_Of_Java

### ISSUE THREAD

**Issue by nikharepriyant** [jitacm/-30DaysDevChallenge-#180]
*Project Idea: OTP Generator*

*Overview*
We propose to add an OTP (One-Time Password) generator to the `30_days_of_java` folder in the `30DaysDevChallenge` repository. This project will focus on creating a simple yet effective OTP generation system that can be utilized in various applications to enhance security through two-factor authentication (2FA).

*Features*
- Random OTP Generation: Generate random OTPs of a specified length.
- Configurable OTP Length: Allow users to configure the length of the OTP (e.g., 4, 6, 8 digits).
- Alphanumeric Support: Option to generate OTPs containing alphanumeric characters.
- Validity Period: Set a validity period for the OTP, after which it expires.
- Logging: Basic logging to keep track of OTP generation and usage.

*Implementation Plan*
1. *Set Up Project Structure:*
   - Create necessary packages and classes for the OTP generator.
2. *Generate Random OTPs:*
   - Implement functionality to generate random numerical and alphanumeric OTPs.
3. *Configure OTP Length:*
   - Add configuration options to specify OTP length.
4. *Set Validity Period:*
   - Implement a mechanism to set and check OTP validity.
5. *Logging:*
   - Integrate basic logging to track OTP generation and expiration.

*Technologies*
- Java (core language)

*Expected Outcomes*
- A reusable OTP generator module that can be integrated into various Java applications.
- Enhanced understanding of secure coding practices related to OTP generation and validation.

*Contribution Guidelines (For New Contributors)*
- Fork the repository and create a new branch for the OTP generator project.
- Ensure code quality with appropriate comments and documentation.
- Write unit tests to verify the functionality of the OTP generator.
- Submit a pull request for review.

**Comment by CLOUDyy003** [comment]
Go Ahead and ensure its well documented
