### ISSUE TITLE
Creating an Hangman Game 

### ISSUE THREAD

**Issue by rohansnishad** [jitacm/-30DaysDevChallenge-#19]
### Description:
I would like to create a HangMan Game using Python.Hangman, created in Python! Guess letters to uncover a hidden word while avoiding too many incorrect guesses, or the hangman gets drawn. This simple, interactive game features a command-line interface, an expandable word list, and customizable difficulty levels.

## Features
- Simple and intuitive command-line interface for easy interaction.
- Easily add or modify the list of words for endless variety.
- Keep track of wins and losses to monitor your progress.
- Runs smoothly on various operating systems with Python installed.

**Comment by jitacm** [comment]
anyone can solve this issue!
