### ISSUE TITLE
Pomodoro Clock

### ISSUE THREAD

**Issue by animex007** [jitacm/-30DaysDevChallenge-#21]
# Pomodoro Clock

A simple and functional Pomodoro clock built using HTML, CSS, and JavaScript. The Pomodoro Technique is a time management method that uses a timer to break work into intervals, traditionally 25 minutes in length, separated by short breaks.

## Features

- **25-minute Work Sessions**: Focus on a task for 25 minutes.
- **5-minute Breaks**: Take a short break after each session.
- **Start/Pause Functionality**: Easily start or pause the timer.
- **Reset Functionality**: Reset the timer to the initial state.

## Expected Behavior

- The timer should reset to 25:00 for a work session if the session is currently active.
- The timer should reset to 5:00 for a break session if the break session is currently active.

**Comment by jitacm** [comment]
go Ahead!
