### ISSUE TITLE
ATM Simulation System / 30_Days_Of_Java

### ISSUE THREAD

**Issue by nikharepriyant** [jitacm/-30DaysDevChallenge-#221]
**Title: ATM Simulation System**

**Description:**
I would like to propose a new project for the `30DaysDevChallenge` repository under the `30_days_of_java` folder. The project idea is to develop an ATM Simulation System.

**Project Overview:**
The ATM Simulation System will simulate the basic functionalities of an ATM machine, including user authentication, balance inquiry, cash withdrawal, deposit, and transaction history. The project will aim to provide a hands-on experience with Java programming concepts, such as object-oriented design, exception handling, and file operations.

**Key Features:**
- User Authentication: Login with a PIN.
- Balance Inquiry: Check current account balance.
- Cash Withdrawal: Withdraw funds with appropriate checks.
- Deposit Funds: Deposit money into the account.
- Transaction History: View past transactions.

**Additional Notes:**
- The system should handle basic error scenarios, such as incorrect PIN entries and insufficient funds.
- Use Java Swing or a similar library for the graphical user interface (GUI).
- Implement a simple data storage mechanism (e.g., file-based or in-memory) to keep track of user accounts and transactions.

Please let me know if you have any questions or need further details. Looking forward to your feedback!

**Comment by Shlokwankhade** [comment]
Go Ahead With Your Issue
