### ISSUE TITLE
30 days of C/C++ - Graph Representation Algorithm

### ISSUE THREAD

**Issue by Walayhs** [jitacm/-30DaysDevChallenge-#24]
_Request for addtion of mentioned project_

## Graph Representation Algorithm
   
 Implementation of  basic graph representations using adjacency lists and adjacency matrices and create functions to add and remove edges and nodes.

Features:
- Using of adjacency lists and adjacency matrices for addition and removal of edges 
- Designing functions to add and remove edges and nodes
- Visualization of graphs, nodes and edges
- Implementation of Basic Graph Transversal Algorithms

**Comment by jitacm** [comment]
go ahead !

**Comment by jitacm** [comment]
done !
