### ISSUE TITLE
Simple Calculator / 30_Days_Of_Java

### ISSUE THREAD

**Issue by AnshNikhare** [jitacm/-30DaysDevChallenge-#243]
### Objective:
To design and develop a simple yet functional calculator application using Java with a graphical user interface (GUI). The calculator will perform basic arithmetic operations such as addition, subtraction, multiplication, and division, providing users with an intuitive and visually appealing tool for quick calculations.

### Project Scope:
Develop a desktop-based application using Java Swing for the GUI.
Provide a user-friendly interface with buttons for digits (0-9) and arithmetic operators (+, -, *, /).
Include functionalities like Clear (C), Equals (=), and Backspace.
Ensure real-time error handling for invalid operations (e.g., division by zero).
Implement memory functions to store and recall values.
Make the calculator responsive to both mouse clicks and keyboard inputs.

### Tools & Technologies:
Programming Language: Java
GUI Framework: Swing
Development Environment: IntelliJ IDEA, Eclipse, or NetBeans
Version Control: Git/GitHub

### Deliverables:
A fully functional calculator application with a responsive GUI.
Project documentation including the README file.

**Comment by Shlokwankhade** [comment]
Go Ahead With Your Issue
