### ISSUE TITLE
Palindrome Checker / 30_Days_Of_Java

### ISSUE THREAD

**Issue by AnshNikhare** [jitacm/-30DaysDevChallenge-#244]
### Objective:
The primary goal of this project is to develop a user-friendly Java-based application with a graphical user interface (GUI) that checks if a given string is a palindrome. A palindrome is a word, phrase, number, or other sequences of characters that reads the same forward and backward (ignoring spaces, punctuation, and capitalization).

### Scope:
The Palindrome Checker will offer a simple yet functional interface that allows users to input text and receive immediate feedback on whether the input is a palindrome. The project will include error handling, ensuring the application can manage various input types, including empty strings and non-alphanumeric characters.

### Features:

- Input Field: A text field where users can enter a string.
- Check Button: A button to trigger the palindrome check.
- Output Display: A label or text area that displays whether the input is a palindrome.
- Clear Button: A button to clear the input and output fields.
- Case and Punctuation Insensitivity: The checker will ignore case and non-alphanumeric characters when determining if a string is a palindrome.
- Error Handling: The application will handle unexpected inputs gracefully, providing appropriate feedback to the user.

### Tools and Technologies:
Programming Language: Java
GUI Framework: Swing
IDE: IntelliJ IDEA, Eclipse, or any other Java IDE
Version Control: Git

Expected Outcomes:
A fully functional Palindrome Checker application with a clean and intuitive user interface.
A comprehensive README file documenting the project, including usage instructions, code structure, and examples.

**Comment by Walayhs** [comment]
Can you provide an image as example?

**Comment by AnshNikhare** [comment]
Sure.
![Screenshot 2024-08-09 155031](https://github.com/user-attachments/assets/e8983d1e-981a-4436-bdc2-18e3b1d740b2)

**Comment by Shlokwankhade** [comment]
Go Ahead With Your Issue
