### ISSUE TITLE
30 days of C/C++ - Pathfinding Visulizer

### ISSUE THREAD

**Issue by Walayhs** [jitacm/-30DaysDevChallenge-#25]
_Request for addtion of mentioned project_

## Pathfinding Visualizer

Implementation of graph transversal algorithms to create a visual representation of graphs and calculation of paths (shortest and longest path).

Features:
- Create a visual representation of the algorithms such as DFS, BFS, Dijkstra, A* and many more if required
- Optimizing for Path Selection
- Calculation of shortest and longest paths 
- Visulization of such an optimized path

**Comment by jitacm** [comment]
go ahead!

**Comment by jitacm** [comment]
@Walayhs it's been more than 5 days, we have not gotten PR related to this!

**Comment by Walayhs** [comment]
Sorry for the delay, the PR related to this project will be created soon for review.
