### ISSUE TITLE
Github_Profile_Viewer/30_days_of_javascript

### ISSUE THREAD

**Issue by ghost** [jitacm/-30DaysDevChallenge-#251]
### Request to Add GitHub Profile Viewer Project

**Project Name**: GitHub Profile Viewer

**Description**: This project is a simple web application that allows users to search and view GitHub profiles using the GitHub API. It displays user information, including their avatar, followers, following, and repositories.

**Features**:
- Search GitHub users by username.
- Display profile information such as avatar, followers, and repositories.
- View the latest repositories of the user.

**Reason for Addition**:
This project aligns with the goals of this repository by providing a useful tool for developers to easily access and view GitHub user profiles. It is built using HTML, CSS, and JavaScript, making it a lightweight and accessible tool for web developers.

Please consider adding this project to the repository. Thank you for your consideration.

![image](https://github.com/user-attachments/assets/818c68e6-6b95-4097-be09-bf56e9d0e2a6)

**Comment by Walayhs** [comment]
Go ahead!
