### ISSUE TITLE
Breadth-First Search Algorithm/30_Days_of_Python

### ISSUE THREAD

**Issue by pratikshabhujade** [jitacm/-30DaysDevChallenge-#254]
Title : Shortest Path Finder in a Maze using Breadth-First Search (BFS)
This project is a Python-based implementation of the Breadth-First Search (BFS) algorithm to find the shortest path in a maze. It utilizes the curses library to create a terminal-based interface that visualizes the maze and the pathfinding process in real-time.

**Features**
1. Maze Representation:
The maze is represented as a 2D grid where walls are denoted by #, the start point by O, and the endpoint by X. The open paths are represented by spaces.

2. Breadth-First Search (BFS) Algorithm:
The BFS algorithm is used to explore all possible paths from the start point to the endpoint. It guarantees finding the shortest path by exploring all nodes at the present depth level before moving on to nodes at the next depth level.

3. Real-Time Visualization:
As the BFS algorithm explores the maze, the pathfinding process is visualized in the terminal. The curses library allows the maze to be dynamically updated, showing the current path being explored in red (X), while the rest of the maze remains in blue.

4. Interactive Terminal Interface:
The program runs in the terminal and waits for user input before closing, allowing users to observe the final path and maze configuration.

5. Customizing the Maze:
The maze structure is defined within the script as a list of lists. You can customize the maze by modifying this list, changing the positions of walls (#), the start point (O), and the endpoint (X).

**Educational Value**
1. Algorithm Visualization:
This project serves as a great educational tool for understanding how the BFS algorithm works. The real-time visualization helps in comprehending the step-by-step process of pathfinding and how BFS ensures the shortest path is found.

2. Terminal-Based UI with Curses:
It also provides an introduction to using the curses library for creating interactive, text-based user interfaces in the terminal.

**Future Enhancements**
•Larger and More Complex Mazes: Expanding the maze grid to include larger and more complex layouts, increasing the challenge and utility of the solver.
•Pathfinding Animation Speed Control: Allowing users to control the speed of the BFS visualization.
•Different Algorithms: Implementing other pathfinding algorithms like Depth-First Search (DFS) or A* for comparison.

https://github.com/user-attachments/assets/1a21a82f-53d2-4c06-912e-fa4f8d44013a

**Comment by Walayhs** [comment]
Go ahead!
