### ISSUE TITLE
Supermarket Billing System / 30_Days_Of_Java

### ISSUE THREAD

**Issue by nikharepriyant** [jitacm/-30DaysDevChallenge-#262]
### Title:
**Supermarket Billing System**

### Description:
I am proposing to develop a **Supermarket Billing System** as part of the 30DaysDevChallenge under the 30_days_of_java folder. This project will focus on creating a console-based billing application that handles basic supermarket operations such as item listing, price calculation, and generating bills for customers. 

### Key Features:
- **Item Management:** Add, edit, and delete items with their respective prices.
- **Billing System:** Calculate total costs, apply discounts, and generate bills.
- **User Interface:** Simple, text-based interface for ease of use.
- **Receipt Generation:** Print or save customer receipts.
- **Error Handling:** Robust error handling for common user input errors.

This project will help enhance my understanding of Java fundamentals while applying them to a practical, real-world problem.

**Comment by Walayhs** [comment]
Go ahead!
