### ISSUE TITLE
Real-Time Chat App / 30_days_of_JavaScript

### ISSUE THREAD

**Issue by Bharat00007** [jitacm/-30DaysDevChallenge-#270]
The current version of the chat application has a functional UI but lacks the modern, user-friendly design elements that are standard in today's chat applications. The user experience could be significantly improved by incorporating a more attractive and functional UI.

**Problem:**

The existing UI is basic and lacks visual appeal, making the chat experience less engaging.
It does not include user avatars, which can make the chat feel impersonal.
There is no differentiation between sent and received messages, making it harder for users to follow the conversation.
The input and send button design is simplistic, and there are no animations or hover effects to enhance interactivity.

**Proposed Solution:**

A complete UI overhaul with the following features:

**User Avatars and Chat Header:**

Added a chat header that includes user avatars and options for settings and logout, creating a more personalized chat experience.

**Differentiated Chat Bubbles:**

Introduced distinct chat bubbles for sent and received messages. Sent messages are aligned to the right with a blue background, while received messages are aligned to the left with a grey background.

**Animated Message Bubbles:**

Added subtle animations to message bubbles to make their appearance smoother and more engaging.

Improved Input and Button Design:

Enhanced the design of the message input field and the send button with rounded edges, shadows, and hover effects to create a more modern look and feel.

**Header Buttons with Hover Effects:**

Included settings and logout buttons in the chat header, with hover effects for better user experience.

**Scrollbars Customization:**

Customized the scrollbars for the chat container to blend with the overall design, ensuring a clean and seamless interface.

![Screenshot 2024-08-11 185017](https://github.com/user-attachments/assets/eef6b59c-ad3e-434f-a335-35b54ec7b737)

**Comment by Walayhs** [comment]
Go ahead!
