### ISSUE TITLE
Admission Councelling System / 30_Days_of_Java 

### ISSUE THREAD

**Issue by Bharat00007** [jitacm/-30DaysDevChallenge-#277]
**### Title: Java-based Admission Counseling System**

**Description**

This pull request introduces a comprehensive Java-based Admission Counseling System designed to streamline the process of college admissions. The system is built to facilitate various stages of the admission process, including student registration, choice selection, seat allocation, and audit tracking. The functionality is implemented through a series of Java classes and forms, each responsible for a specific aspect of the system.

**Key Features and Files**

1. **Student Registration and Authentication:**

The system supports a robust student registration process. Students can sign up, log in, and update their profiles. Their data is securely managed, ensuring privacy and security.

2. **Choice Selection:**

The Choice.form file enables students to select their preferred colleges and courses based on their eligibility and rank. This form ensures that students can make informed decisions during the counseling process.

3. **Seat Allocation:**

The system includes an algorithm for seat allocation, ensuring that students are allocated seats based on their merit, choices, and availability of seats in colleges.

4. **Audit Tracking:**

The Audit_details.java and Audit_details.form files are designed to maintain a detailed log of the actions taken by users and administrators within the system. This feature is crucial for ensuring transparency and accountability during the counseling process.

5. **Admin Dashboard:**

An administrative interface allows authorized personnel to manage the entire admission process, from verifying student credentials to finalizing seat allocation. The admin dashboard is intuitive and provides real-time insights into the ongoing process.

**Comment by Shlokwankhade** [comment]
Go Ahead With Your Issue
