### ISSUE TITLE
Contact Book Application / 30_Days_Of_Java

### ISSUE THREAD

**Issue by AnshNikhare** [jitacm/-30DaysDevChallenge-#286]
# Project Proposal - Contact Book Application

## Project Overview

The Contact Book Application is a Java-based desktop application with a graphical user interface (GUI) for managing personal contacts. The application allows users to add, edit, delete, and search for contacts while also grouping them into categories. Contact information such as name, phone number, and email is stored persistently, ensuring that the data is saved even after the application is closed.

## Features

- **Add, Edit, and Delete Contacts:** Users can easily manage their contacts by adding new entries, editing existing ones, or deleting them.
- **Store Contact Information:** The application allows the storage of essential contact details, including name, phone number, and email.
- **Search for Contacts:** Users can search for specific contacts using keywords.
- **Persistent Data Storage:** All contact information is saved and loaded automatically when the application is reopened.

## Technology Stack

- **Programming Language:** Java
- **GUI Framework:** Swing
- **Data Persistence:** Serialization (Java I/O)

## Project Structure

- **Contact.java:** This class represents an individual contact, holding details such as name, phone number, and email.
- **ContactBook.java:** This class manages a collection of contacts, providing methods to add, edit, delete, and search for contacts.
- **ContactBookGUI.java:** This class handles the graphical user interface, providing an interactive way for users to manage their contacts.
- **Main.java:** The entry point of the application, initializing the GUI and loading any previously saved contacts.

## Conclusion

The Contact Book Application aims to provide a simple yet powerful tool for managing personal contacts. With an intuitive GUI and persistent data storage, users can efficiently organize and retrieve their contacts with ease.

**Comment by Shlokwankhade** [comment]
Go Ahead With Your Issue
