### ISSUE TITLE
30DaysOfFlutter - QR Generator 

### ISSUE THREAD

**Issue by rohansnishad** [jitacm/-30DaysDevChallenge-#31]
# Description
This Flutter project aims to develop a robust QR scanner and generator mobile application. The app facilitates the scanning of QR codes for various purposes such as accessing website URLs, adding contacts, making payments, or unlocking content. Additionally, it enables users to generate custom QR codes for sharing information conveniently. With a user-friendly interface and seamless functionality, this app simplifies QR code interactions for users, making it a handy tool for everyday use.

## Objective:
- Streamlines QR code scanning and generation processes for user convenience.
- Offers a user-friendly interface with intuitive controls for easy navigation.
- Provides reliable and accurate QR code scanning functionality, supporting various types of QR codes.
- Enables customization options for generating QR codes, such as specifying content and design.
- Ensures compatibility with different devices and operating systems for widespread usability.

**Comment by jitacm** [comment]
go ahead !
