### ISSUE TITLE
Online Voting System / 30_Days_Of_Java

### ISSUE THREAD

**Issue by AnshNikhare** [jitacm/-30DaysDevChallenge-#338]
# Project Proposal - Online Voting System

## Description

The `Online Voting System` is a Java-based application that provides a digital platform for users to register, cast votes, and tally results in a secure and user-friendly manner. This application features a graphical user interface (GUI) and ensures data persistence using serialization, allowing for smooth operation even after closing the app. The system is designed to handle the voting process efficiently, including voter registration, vote casting, and offers clear and accurate tallying of results.

## Features

- **Voter Registration:** Allows users to register as voters with their details.
- **Vote Casting:** Voters can cast their votes for one of the three chairpersons: NARENDRA MODI, RAHUL GANDHI, or KEJRIWAL.
- **Result Tallying:** The system tallies votes and displays the results.
- **Data Persistence:** All voter and voting data is stored persistently using serialization, ensuring that data is not lost when the application is closed.
- **Clean and Attractive GUI:** The application features a clean and beautiful interface, making it easy to use.

## Technologies Used

- Java
- Swing (for GUI)
- Serialization (for data persistence)

**Comment by Shlokwankhade** [comment]
Go Ahead
