### ISSUE TITLE
Personal Library Catalog / 30_Days_Of_Java

### ISSUE THREAD

**Issue by AnshNikhare** [jitacm/-30DaysDevChallenge-#340]
# New Project Proposal - Personal Library Catalog

A Java application with a graphical user interface for managing a personal library catalog.

## Features

- Add books to your personal library
- Track borrowed and returned books
- Search for books by title, author, or genre
- Rate and review books

## Usage

1. **Adding a Book**: Fill in the title, author, and genre fields, then click "Add Book".
2. **Removing a Book**: Select a book from the list and click "Remove Book".
3. **Borrowing/Returning a Book**: Select a book and click "Borrow Book" or "Return Book".
4. **Searching for Books**: Enter a search term, select the search type (Title, Author, or Genre), and click "Search".
5. **Rating and Reviewing**: Select a book, set the rating using the spinner, enter a review in the text area, and click "Add Book" to update.

**Comment by Shlokwankhade** [comment]
Go Ahead
