### ISSUE TITLE
Simple Interest Calculator / 30_Days_Of_Java

### ISSUE THREAD

**Issue by AnshNikhare** [jitacm/-30DaysDevChallenge-#345]
# Project Proposal: Simple Interest Calculator

## Project Overview

The Simple Interest Calculator is a Java-based desktop application with a graphical user interface (GUI) designed to calculate the simple interest given the principal amount, rate of interest, and time period. The application aims to provide a user-friendly and intuitive experience for users to quickly compute simple interest, which is a fundamental financial calculation.

## Objectives

- Develop a Java application that calculates simple interest.
- Design a clean, modern, and easy-to-use GUI using Swing components.
- Implement error handling to ensure the application responds appropriately to invalid input.
- Provide an option to reset the form to facilitate multiple calculations in a single session.

## Features

- **Input Fields**: Text fields for the user to input the principal amount, rate of interest, and time period.
- **Calculate Button**: Computes the simple interest when clicked.
- **Reset Button**: Clears all input fields and the result field, allowing for a fresh calculation.
- **Result Display**: Shows the calculated simple interest in a non-editable text field.
- **Error Handling**: Alerts the user with a message dialog if the input is invalid.

## Technologies Used

- **Java**: The core programming language used to develop the application.
- **Swing**: Java's built-in GUI widget toolkit used for building the user interface.

## Target Audience

This application is targeted at:

- Students learning about simple interest calculations in mathematics or finance.
- Professionals who require quick and easy simple interest calculations.
- Anyone needing a straightforward tool for financial calculations.

## Success Criteria

- The application successfully calculates simple interest and displays it to the user.
- The user interface is intuitive, clean, and error-free.
- The application handles invalid input gracefully, without crashing.

**Comment by Shlokwankhade** [comment]
Go Ahead
