### ISSUE TITLE
Train Ticket Management System / 30_Days_Of_Java

### ISSUE THREAD

**Issue by AnshNikhare** [jitacm/-30DaysDevChallenge-#346]
# New Project Proposal - Train Ticket Management System

## Project Overview

The Train Ticket Management System is a Java Swing application designed to manage train ticket bookings. It allows users to select a destination, specify the number of tickets they want to purchase, and generate a receipt after the purchase. The system provides a simple graphical user interface (GUI) for users to interact with and handle basic ticket management tasks.

## Objectives

- To create a user-friendly GUI application for managing train tickets.
- To allow users to select a destination from a predefined list.
- To enable users to enter the number of tickets they wish to purchase.
- To calculate the total cost based on the number of tickets.
- To generate and display a receipt after the purchase, including user details and ticket information.

## Features

1. **Destination Selection**: Users can choose from a list of predefined destinations.
2. **Ticket Quantity Input**: Users can specify the number of tickets they wish to buy.
3. **Cost Calculation**: The application calculates the total cost based on the number of tickets.
4. **Receipt Generation**: After purchasing, the system generates a receipt that includes the user's name, destination, number of tickets, and total cost.
5. **Input Validation**: The system checks for valid input and provides user feedback.

## Technical Requirements

- **Language**: Java
- **GUI Framework**: Swing
- **Cost Calculation**: Hardcoded cost per ticket for simplicity

**Comment by Shlokwankhade** [comment]
Go Ahead
