### ISSUE TITLE
A Random Number Guessing Program Generated by The machine

### ISSUE THREAD

**Issue by Axwell-2** [jitacm/-30DaysDevChallenge-#50]
Description : The "Guess the Number" game is a simple, interactive game where the computer randomly selects a number within a specified range (typically between 1 and 100), and the player attempts to guess this number. After each guess, the game provides feedback indicating whether the guess was too high, too low, or correct. The game continues until the player correctly guesses the number, at which point the game congratulates the player and displays the number of attempts made.

Application : Learning Basic Control Structures: It introduces beginners to loops (for repeatedly prompting for guesses) and conditionals (for evaluating each guess).
Working with Random Numbers: It demonstrates the use of the random module to generate random numbers, a common task in many programming scenarios.
User Input and Output: It provides practice with getting input from users and displaying output, essential for any interactive program.
Problem-Solving Skills: It encourages logical thinking and problem-solving, as players must use the feedback to narrow down their guesses.

**Comment by jitacm** [comment]
go ahead !
