### ISSUE TITLE
Combined Database Maintenance and User Management Shell Script

### ISSUE THREAD

**Issue by Surajh09** [jitacm/-30DaysDevChallenge-#57]
#### Description

Currently, we have developed a shell script that combines database maintenance tasks (backup, vacuum, reindex) with user management tasks (add, remove, modify). The script aims to automate these operations on a Linux system.

#### Current Features

- **Database Maintenance:**
  - Backup PostgreSQL database.
  - Vacuum and reindex operations.

- **User Management:**
  - Add users from a predefined list.
  - Remove users (functionality present but commented out for safety).
  - Placeholder for modifying user details.

#### Issue

1. **Enhancement Request:** Modify the user management function to allow modification of user details.
2. **Documentation:** Update `README.md` to include detailed setup instructions and usage examples.
3. **Testing:** Perform thorough testing to ensure script reliability and error handling.

#### Additional Information

- **Expected Behavior:** The `modify_user` function should allow changing user attributes such as username, home directory, and shell.
- **Impact:** This enhancement will improve the script's functionality, making it more versatile for managing user accounts in diverse environments.
- **Environment:** Developed and tested on Ubuntu 20.04 with PostgreSQL 12. Additional testing on different distributions and database versions may be necessary.

#### Related Files

- `maintenance_and_users.sh`: Main script file.
- `README.md`: Current documentation file.

#### Steps to Reproduce (Optional)

- Execute `modify_user` function with parameters to demonstrate intended changes.
- Note any errors or issues encountered during testing.

#### Proposed Solution

- Implement user input validation to ensure secure modification of user attributes.
- Provide clear error messages and logging for debugging purposes.

**Comment by jitacm** [comment]
go ahead !
