### ISSUE TITLE
Enhancements to Combined Database Maintenance and User Management Script

### ISSUE THREAD

**Issue by Surajh09** [jitacm/-30DaysDevChallenge-#62]
Currently, we have developed a shell script that combines database maintenance tasks (backup, vacuum, reindex) with user management tasks (add, remove, modify). The script aims to automate these operations on a Linux system.

#### Current Features

- **Database Maintenance:**
  - Backup PostgreSQL database.
  - Vacuum and reindex operations.

- **User Management:**
  - Add users from a predefined list.
  - Remove users (functionality present but commented out for safety).
  - Placeholder for modifying user details.

**Comment by jitacm** [comment]
go ahead !
