### ISSUE TITLE
Tic-Tac-Toe/30_Days_Of_Python

### ISSUE THREAD

**Issue by Anjali0903** [jitacm/-30DaysDevChallenge-#73]
**Description.**

This is a simple game made with Python language, without using any graphical library.

**Comment by animex007** [comment]
GO ahead !

**Comment by jitacm** [comment]
Hey @Anjali0903 , Is your project ready to push ? we have to close the python domain.

**Comment by CLOUDyy003** [comment]
@Anjali0903 Is your code ready to push? I would like to continue this issue.
