### ISSUE TITLE
Expense Tracker / 30 Days Of Python

### ISSUE THREAD

**Issue by sanskruti-kokde** [jitacm/-30DaysDevChallenge-#77]
The Expense Tracker is a simple Python application that helps users manage their finances by tracking their expenses and income. Users can add, categorize, and view transactions to get an overview of their financial situation.

## FEATURES :

- Add new transactions (income or expense)
- Categorize transactions (e.g., Food, Rent, Utilities)
- View all transactions
- View summary of expenses and income
- Save transaction data to a file for persistence

**Comment by jitacm** [comment]
go ahead !

**Comment by jitacm** [comment]
Hey @sanskruti-kokde , Is your project ready to push ? we have to close the python domain.
