### ISSUE TITLE
UAV detector

### ISSUE THREAD

**Issue by lukey2207** [jitacm/-30DaysDevChallenge-#79]
This helps to detect any flying object in air.
it can be drone or aeroplanes

**Comment by jitacm** [comment]
Please mention the language and algorithm you are using !

**Comment by lukey2207** [comment]
> Please mention the language and algorithm you are using !

using python with deep learning.

**Comment by jitacm** [comment]
Hey @lukey2207, Is your project ready to push ? we have to close the python domain.

**Comment by lukey2207** [comment]
> Hey @lukey2207, Is your project ready to push ? we have to close the python domain.

Yes it is ready
