### ISSUE TITLE
30 days of javascript - RPN Calculator

### ISSUE THREAD

**Issue by animex007** [jitacm/-30DaysDevChallenge-#8]
### Description

# Title: Reverse Polish Notation (RPN) Calculator 

##   Overview
I'm proposing the development of a Reverse Polish Notation (RPN) calculator. RPN is a mathematical notation in which every operator follows all of its operands, providing a unique and efficient way of performing calculations. 

## Project Goals
The primary goal of this project will be to create a fully functional RPN calculator that can handle basic arithmetic operations as well as more complex mathematical functions. 

## Features
- Support for basic arithmetic operations (addition, subtraction, multiplication, division)
- Implementation of additional mathematical functions (trigonometric functions, logarithms, exponentiation)
- Error handling for invalid input and operations
- User-friendly interface (command-line or graphical)

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct]

**Comment by jitacm** [comment]
@animex007 go ahead !!
